[build]
  publish = "dist"
  command = "npm install && npm run build:prod"

[build.environment]
  NODE_VERSION = "20"

# رؤوس أمان أساسية

[[headers]]
  for = "/brand/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"

# إعادة توجيه بسيطة لـ HTTPS
[[redirects]]
  from = "http://smartstart-ai.net/*"
  to = "https://smartstart-ai.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.smartstart-ai.net/*"
  to = "https://www.smartstart-ai.net/:splat"
  status = 301
  force = true
